apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-cicd-app
  namespace: default
  labels:
    app: eks-cicd-app
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: eks-cicd-app
  template:
    metadata:
      labels:
        app: eks-cicd-app
        version: v1
    spec:
      containers:
      - name: eks-cicd-app
        image: ${ECR_REPOSITORY_URL}:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: APP_VERSION
          value: "${IMAGE_TAG}"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1001
      serviceAccountName: eks-cicd-app-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-cicd-app-sa
  namespace: default
  labels:
    app: eks-cicd-app
automountServiceAccountToken: false