apiVersion: v1
kind: Service
metadata:
  name: eks-cicd-app-service
  namespace: default
  labels:
    app: eks-cicd-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: eks-cicd-app
---
apiVersion: v1
kind: Service
metadata:
  name: eks-cicd-app-internal
  namespace: default
  labels:
    app: eks-cicd-app
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: eks-cicd-app