apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: online-shop
  labels:
    app.kubernetes.io/name: online-shop
    app.kubernetes.io/component: config
data:
  # Application Environment
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  NODE_ENV: "production"
  
  # Service Discovery
  USER_SERVICE_URL: "http://user-service:8080"
  PRODUCT_SERVICE_URL: "http://product-service:8080"
  ORDER_SERVICE_URL: "http://order-service:8080"
  PAYMENT_SERVICE_URL: "http://payment-service:8080"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Database Configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "shopdb"
  DB_USER: "shopuser"
  
  # MongoDB Configuration (for order service)
  MONGO_HOST: "mongodb-service"
  MONGO_PORT: "27017"
  MONGO_DATABASE: "orders"
  
  # Rate Limiting
  RATE_LIMIT: "100"
  
  # CORS Configuration
  ALLOWED_ORIGINS: "http://localhost:3000,https://shop.example.com"
  
  # Health Check Configuration
  HEALTH_CHECK_INTERVAL: "30"
  HEALTH_CHECK_TIMEOUT: "5"
  
  # Prometheus Metrics
  METRICS_PORT: "9090"
  METRICS_PATH: "/metrics"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: online-shop
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: config
data:
  redis.conf: |
    # Redis Configuration
    bind 0.0.0.0
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    logfile ""
    databases 16
    always-show-logo yes
    
    # Memory Management
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    
    # Security
    # requirepass will be set via secret
    
    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data
    
    # Replication
    replica-serve-stale-data yes
    replica-read-only yes
    
    # Performance
    slowlog-log-slower-than 10000
    slowlog-max-len 128
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: online-shop
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: config
data:
  POSTGRES_DB: "shopdb"
  POSTGRES_USER: "shopuser"
  PGDATA: "/var/lib/postgresql/data/pgdata"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: online-shop
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: config
data:
  MONGO_INITDB_DATABASE: "orders"
  MONGO_INITDB_ROOT_USERNAME: "admin"